export const FETCH_TASK_LIST = "FETCH_TASK_LIST";
export const FETCH_TASK_LIST_SUCCESS = "FETCH_TASK_LIST_SUCCESS";
export const FETCH_TASK_LIST_ERROR = "FETCH_TASK_LIST_ERROR";

export const FETCH_TASK_DETAILS = "FETCH_TASK_DETAILS";
export const FETCH_TASK_DETAILS_SUCCESS = "FETCH_TASK_DETAILS_SUCCESS";
export const FETCH_TASK_DETAILS_ERROR = "FETCH_TASK_DETAILS_ERROR";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

export const DELETE_TASKS = "DELETE_TASKS";
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_ERROR = "DELETE_TASKS_ERROR";

export const CHANGE_FILTERS = "CHANGE_FILTERS";
