export const FETCH_TASK_LIST = "FETCH_TASK_LIST";
export const FETCH_TASK_LIST_SUCCESS = "FETCH_TASK_LIST_SUCCESS";

export const FETCH_TASK_DETAILS = "FETCH_TASK_DETAILS";
export const FETCH_TASK_DETAILS_SUCCESS = "FETCH_TASK_DETAILS_SUCCESS";

export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASKS = "DELETE_TASKS";

export const CHANGE_FILTERS = "CHANGE_FILTERS";
